model:
  learning_rate: 1e-4
  matched_loss_weight: .5
  descriptor:
    class_path: 'models.feature_extractor.SIFTFeatureExtractor'
    init_args:
      rootsift: false

data:
  num_kps: 100
  batch_size: 1
  num_workers: 20
  train_image_transform: ['column_norm']
  test_image_transform: ['column_norm']

trainer:
  logger:
    - class_path: WandbLogger
      init_args:
        project: 'sss-corr-training'
        name: '220824-sift-col-norm-test-addnoisy'
        log_model: 'all'
        dir: 'training'
