trainer:
  max_epochs: 2
  #TODO: Configure wandb logger correctly!
  accelerator: 'gpu'
  devices: 1
  gradient_clip_val: .5
  detect_anomaly: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: 'val/loss'
        mode: 'min'
        patience: 5
        check_finite: true
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: 'val/loss'
        dirpath: './220816_training_setup'
        filename: 'sss-epoch{epoch:02d}-val-loss{val/loss:.2f}'
        save_top_k: 3

data:
  root: '/home/li/Documents/sss-correspondence/data/GullmarsfjordSMaRC20210209_ssh_annotations/survey2_better_resolution/9-0169to0182-nbr_pings-1301_annotated/patch240_step40_test0.1_refSSH-0170_OrderedDict/'
  num_workers: 0