model:
  keypoint_encoder:  [32, 64, 128, 256]
  sinkhorn_iterations: 100
  match_threshold: .2
  # N.B. NOT correct YAML syntax! Need to write out all layers...
  # gnn_layers: ['self', 'cross'] * 9

data:
  root: '/home/li/Documents/sss-correspondence/data/GullmarsfjordSMaRC20210209_ssh_annotations/survey2_better_resolution/9-0169to0182-nbr_pings-1301_annotated/patch240_step40_test0.1_refSSH-0170_OrderedDict/'
  min_overlap: .2
  eval_split: .1
  data_kwargs:
    a_max: 3.
    gaussian_blur_kernel_size: [3, 3]
    color_jitter_brightness: .5
    color_jitter_contrast: .5
    color_jitter_saturation: .5
    sharpness_factor: 2

trainer:
  accelerator: 'gpu'
  devices: 1
  gradient_clip_val: .5
  detect_anomaly: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: 'val/loss'
        mode: 'min'
        patience: 3
        check_finite: true
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: 'val/loss'
        filename: 'sss-{epoch:02d}-{val/loss:.2f}'
        save_top_k: 3
    - class_path: models.logging_callbacks.LogImagesCallback