data:
  root: '/home/li/Documents/sss-correspondence/data/GullmarsfjordSMaRC20210209_ssh_annotations/survey2_better_resolution/9-0169to0182-nbr_pings-1301_annotated/patch240_step40_test0.1_refSSH-0170_OrderedDict/'
  num_kps: 100
  min_overlap: .2
  eval_split: .1
  batch_size: 10
  num_workers: 10
  train_image_transform: ['column_norm', 'image_aug']
  test_image_transform: ['column_norm']
  data_kwargs:
    a_max: 3.
    gaussian_blur_kernel_size: [3, 3]
    color_jitter_brightness: .5
    color_jitter_contrast: .5
    color_jitter_saturation: .5
    sharpness_factor: 2