trainer:
  max_epochs: 1
  logger:
    - class_path: WandbLogger
      init_args:
        project: 'sss-corr'
        name: '220817_training_setup'
        log_model: 'all'
        dir: '.'
  accelerator: 'gpu'
  devices: 1
  gradient_clip_val: .5
  detect_anomaly: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: 'val/loss'
        mode: 'min'
        patience: 5
        check_finite: true
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: 'val/loss'
        filename: 'sss-{epoch:02d}-{val/loss:.2f}'
        save_top_k: 3
    - class_path: pytorch_lightning.callbacks.StochasticWeightAveraging
      init_args:
        swa_lrs: .05
        swa_epoch_start: .5
    - class_path: models.logging_callbacks.LogImagesCallback

